# Site settings
title: Dan Schrimpsher, PhD
twitter_username: dschrimpsher
name: Dan Schrimpsher

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://spacepragmatism.blogspot.com/
 - title: GitHub
   url: https://github.com/dschrimpsher
 - title: StackOverflow
   url: https://stackoverflow.com/users/2430385/dr-code-monkey
 - title: DZone
   url: https://dzone.com/users/4031498/drcodemonkey.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/danschrimpsher

#Any buzzword skills you want to include
skills:
 - Python
 - Node.js
 - C/C++
 - Java
 - MongoDB
 - MySQL
 - Ontology/Knowledge Bases
 - API design
 - Java
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Work experience is required
roles:
 - title: Lead Software Developer
   start: 2013
   end: Ongoing
   employer: CableLabs
   description: Principal member of the Future Infastructures Group, working on various projects related to machine learning, edge computing, network virtualization, programable data plane, 5G/LTE, low power networks for IoT, PKI Certificates, intent based networks, RESTful web services, SQL & NoSQL database integration, and embedded systems.
 - title: Senior Software Engineer
   start: 2011
   end: 2016
   employer: Terma North America, Inc.
   description: Defense Service Engineering supporting Airborne Systems, Radar Systems, and Command and Control systems.
 - title: Adjunct Professor of Computer Science
   start: 2008
   end: 2012
   employer: University of Alabama in Huntsville
   description: Taught graduate and undergraduate courses in Computer Science including, C/C++, Java, Unix, Digital Circuits, Data Structures. 
 - title: Principle Software Engineer
   start: 2008
   end: 2011
   employer: Decisive Analytics Corporation
   description: Program manager for condition based maintenance & data fusion group within Missile Defense Algorithms Division (MDAD).  Supervise multiple contracts as well as functioning as Principle Investigator for failure prognostics SBIR with the Army IAMD Project Office (Invited to Phase 2 and Phase 3).  
 - title: Senior Software Engineer
   start: 2005
   end: 2008
   employer: Applied Data Trends
   description: Project lead for joint track management communications solutions for army air and missile defense.  Also serve as a senior developer on the Common Data Link Interfaced tactical communications system for Army LTPO.
 - title: Senior Software Engineer
   start: 2003
   end: 2004
   employer: L3 Communications
   description:
 - title: Principle Engineer
   start: 2002
   end: 2003
   employer: JT3
   description:
 - title: Developer
   start: 2001
   end: 2002
   employer: Phase IV Engineering
   description:
 - title: Programmer Analyst
   start: 1998
   end: 2001
   employer: Teledyne Brown Engineering
   description:


#Education is required
education:
 - level: PhD
   date: 2011
   subject: Computer Science & Statistics
   school: University of Alabama in Huntsville
 - level: Masters of Science (MS)
   date: 1999
   subject: Computer Science
   school: Auburn University
 - level: Bachelor of Science (BS)
   date: 1997
   subject: Computer Engineering
   school: Auburn University

#List of interesting Github repo/projects to include - optional
github:
 - cablelabs/lpwanserver
 - cablelabs/drp-python
 - cablelabs/micronets-manager
 - cablelabs/micronets-identity-service
 - cablelabs/bsa-serviceability
 - cablelabs/snaps-boot
 - cablelabs/snaps-openstack
 - cablelabs/snaps-kubernetes


#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/2430385/dr-code-monkey
   flairimageurl: https://stackoverflow.com/users/flair/2430385.png

intro: |
  Future Infrastructure Group Lead Software Developer. I work with next generation network operations and security, edge computing, web services, machine learning, and a little bit of everything else. I have worked with Python, C/C++, Node.js, and Java in the last two years. I am fluent in MongoDB, MySQL, PostgreSQL, and Oracle, as well as JSON, XML, RDF/OWL, and YAML. 26 years as a Linux/Unix expert.

additionalinfo: |
  <strong>Research Areas</strong>:  <ul>
   <li>Ontologies/Knowledge Bases</li>
   <li>Unsupervised Learning algorithms</li> 
   <li>Intent Based Networking</li> 
   <li>Intelligent Agents.</li>
  </ul>
  <strong>Publications:</strong> <ul>
   <li><strong>Schrimpsher, Dan</strong>, and Letha Etzkorn. "A model to predict quality of a reduced ontology for Web service discovery on mobile devices." <em>The Knowledge Engineering Review</em> 29.2 (2014): 201-216.</li>
   <li><strong>Schrimpsher, Dan</strong>, Zhiqiang Wu, Anthony M. Orme, and Letha Etzkorn."Dynamic ontology version control." <em>Proceedings of the 48th Annual Southeast Regional Conference.</em> ACM, 2010.</li>
   <li><strong>Schrimpsher, Dan</strong>, and Letha Etzkorn. "An empirical quality model for web service ontologies to support mobile devices." <em>2009 3rd International Symposium on Empirical Software Engineering and Measurement.</em> IEEE, 2009.</li>
   <li><strong>Schrimpsher, Dan</strong>, and Letha Etzkorn. "Sub-graphing web service ontologies to support resource constraints of mobile devices." <em>Proceedings of the 47th Annual Southeast Regional Conference.</em> ACM, 2009.</li>
   <li>Narayanan, N. Hari, and <strong>Dan J. Schrimpsher</strong>. "Extending eye tracking to analyse interactions with multimedia information presentations." <em>People and Computers XIV—Usability or Else!.</em> Springer, London, 2000. 271-286.</li>
   <li>Hansen, Steven R., N. Hari Narayanan, and <strong>Dan Schrimpsher</strong>. "Helping learners visualize and comprehend algorithms." <em>Interactive Multimedia Electronic Journal of Computer-Enhanced Learning</em> 2.1 (2000): 10.</li>
  </ul>
  <strong>Patents:</strong><ul>
  <li>Levensalor, R., Pisarski, S.M., Corcimiglia, C.J. and <strong>Schrimpsher, D.</strong>, Cable Television Labs Inc, 2018. <em>Systems and methods for disaggregated software defined networking control.</em> U.S. Patent Application 16/000,721.</li>
  <li>Padden, J., Williams, T.H., Dennis, J.R., Malas, D.W., <strong>Schrimpsher, D.</strong> and Jones, D.D., Cable Television Labs Inc, 2019. <em>Smart taps.</em> U.S. Patent Application 16/154,935.</li>  
  </ul>
