# Site settings
title: Dan Schrimpsher, PhD
twitter_username: dschrimpsher
name: Dan Schrimpsher

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://spacepragmatism.blogspot.com/
 - title: GitHub
   url: https://github.com/dschrimpsher
 - title: StackOverflow
   url: https://stackoverflow.com/users/2430385/dr-code-monkey
 - title: DZone
   url: https://dzone.com/users/4031498/drcodemonkey.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/danschrimpsher

#Any buzzword skills you want to include
skills:
 - Python
 - Node.js
 - C/C++
 - Java
 - MongoDB
 - MySQL
 - Ontology/Knowledge Bases
 - API design
 - Java
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Work experience is required
roles:
 - title: Lead Software Developer
   start: 2013
   end: Ongoing
   employer: CableLabs
   description: Principal member of the Future Infastructures Group, working on various projects related to machine learning, edge computing, network virtualization, programable data plane, 5G/LTE, low power networks for IoT, PKI Certificates, intent based networks, RESTful web services, SQL & NoSQL database integration, and embedded systems.
 - title: Senior Software Engineer
   start: 2011
   end: 2016
   employer: Terma North America, Inc.
   description: Defense Service Engineering supporting Airborne Systems, Radar Systems, and Command and Control systems.
 - title: Adjunct Professor of Computer Science
   start: 2008
   end: 2012
   employer: University of Alabama in Huntsville
   description: Taught graduate and undergraduate courses in Computer Science including, C/C++, Java, Unix, Digital Circuits, Data Structures. 
 - title: Program Manager/Principle Software Engineer
   start: 2008
   end: 2011
   employer: Decisive Analytics Corporation
   description: Program manager for condition based maintenance & data fusion group within Missile Defense Algorithms Division (MDAD).  Supervise multiple contracts as well as functioning as Principle Investigator for failure prognostics SBIR with the Army IAMD Project Office (Invited to Phase 2 and Phase 3).  

#Education is required
education:
 - level: PhD
   date: 2011
   subject: Computer Science & Statistics
   school: University of Alabama in Huntsville
 - level: Masters of Science (MS)
   date: 1999
   subject: Computer Science
   school: Auburn University
 - level: Bachelor of Computer Engineering (BCPE)
   date: 1997
   subject: Computer Engineering
   school: Auburn University

#List of interesting Github repo/projects to include - optional
github:
 - dschrimpsher/dschrimpsher.github.io
 - dschrimpsher/python-example
 - dschrimpsher/docker-example
 - cablelabs/lpwanserver
 - cablelabs/micronets-manager
 - cablelabs/snaps-boot
 - cablelabs/drp-python
 - cablelabs/micronets-identity-service
 - cablelabs/bsa-serviceability
 

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/2430385/dr-code-monkey
   flairimageurl: https://stackoverflow.com/users/flair/2430385.png

intro: |
  Future Infrastructure Group Lead Software Developer. I work with next generation network operations and security, edge computing, web services, machine learning, and a little bit of everything else. I have worked with Python, C/C++, Node.js, and Java in the last two years. I am fluent in MongoDB, MySQL, PostgreSQL, and Oracle, as well as JSON, XML, RDF/OWL, and YAML. 26 years as a Linux/Unix expert.

additionalInfo: |
  Research areas: 
    Ontologies/Knowledge Bases, Unsupervised Learning algorithms, Intent Based Networking, and Intelligent Agents.
  Publications:
    Schrimpsher, Dan, and Letha Etzkorn. "A model to predict quality of a reduced ontology for Web service discovery on mobile devices." The Knowledge Engineering Review 29.2 (2014): 201-216.
    Schrimpsher, Dan, Zhiqiang Wu, Anthony M. Orme, and Letha Etzkorn."Dynamic ontology version control." Proceedings of the 48th Annual Southeast Regional Conference. ACM, 2010.
    Schrimpsher, Dan, and Letha Etzkorn. "An empirical quality model for web service ontologies to support mobile devices." 2009 3rd International Symposium on Empirical Software Engineering and Measurement. IEEE, 2009.
    Schrimpsher, Dan, and Letha Etzkorn. "Sub-graphing web service ontologies to support resource constraints of mobile devices." Proceedings of the 47th Annual Southeast Regional Conference. ACM, 2009.
    Narayanan, N. Hari, and Dan J. Schrimpsher. "Extending eye tracking to analyse interactions with multimedia information presentations." People and Computers XIV—Usability or Else!. Springer, London, 2000. 271-286.
    Hansen, Steven R., N. Hari Narayanan, and Dan Schrimpsher. "Helping learners visualize and comprehend algorithms." Interactive Multimedia Electronic Journal of Computer-Enhanced Learning 2.1 (2000): 10.
  Patents:
    Levensalor, R., Pisarski, S.M., Corcimiglia, C.J. and Schrimpsher, D., Cable Television Labs Inc, 2018. Systems and methods for disaggregated software defined networking control. U.S. Patent Application 16/000,721.
    Padden, J., Williams, T.H., Dennis, J.R., Malas, D.W., Schrimpsher, D. and Jones, D.D., Cable Television Labs Inc, 2019. Smart taps. U.S. Patent Application 16/154,935.
